#
###################################
# Site wide configuration
####################################
#
title: Chenlong Wang
email: clwang88@gmail.com
description: A simple and awesome blog theme powered by jekyll.
keywords: ["Optimization", "Programming", "Data Science"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          Asia/Shanghai
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Chenlong Wang
  avatar: avatar.png
  job: "Algorithm Engineer"
  bio: "I was an applied geophysicist focus on data assimilation, and I am newly working for artificial intelligence laboratory in SAIC Motor, Shanghai."
